import assert from "node:assert/strict";
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { applyModelConfigAsync } from "../extensions/gentle-ai.ts";
import test from "node:test";
import { tmpdir } from "node:os";
import { join } from "node:path";
const root = join(fileURLToPath(new URL("..", import.meta.url))), bin = join(root, "bin", "gentle-pi-models.mjs");
function run(input: unknown) { return spawnSync(process.execPath, [bin], { input: typeof input === "string" ? input : `${JSON.stringify(input)}\n`, encoding: "utf8" }); }
function scratch() { const root = mkdtempSync(join(tmpdir(), "gentle-pi-models-cli-")), cwd = join(root, "project"), agentDir = join(root, "agent"), configHome = join(root, "global"); mkdirSync(cwd, { recursive: true }); return { root, cwd, agentDir, configHome, dispose: () => rmSync(root, { recursive: true, force: true }) }; }
function request(target: ReturnType<typeof scratch>, operation: string, extra: Record<string, unknown> = {}) { return { version: 1, contract: "gentle-pi.model-routing/v1", operation, cwd: target.cwd, agentDir: target.agentDir, target: "project", configHome: target.configHome, ...extra }; }
function agent(path: string, name: string) { mkdirSync(join(path, ".."), { recursive: true }); writeFileSync(path, `---\nname: ${name}\ndescription: test\n---\nbody\n`); }
test("models process returns one JSON invalid-input response and a stable exit class", () => { const result = run("{"); assert.equal(result.status, 2); assert.equal(result.stdout.trim().split("\n").length, 1); const response = JSON.parse(result.stdout); assert.equal(response.ok, false); assert.equal(response.exitClass, "invalid-input"); assert.notEqual(result.stderr.trim(), ""); });
test("capabilities and unsupported contracts are explicit process operations", () => { const supported = run({ version: 1, contract: "gentle-pi.model-routing/v1", operation: "capabilities" }); assert.equal(supported.status, 0); assert.deepEqual(JSON.parse(supported.stdout).result.operations, ["capabilities", "inspect", "validate", "apply"]); const unsupported = run({ version: 2, contract: "gentle-pi.model-routing/v1", operation: "capabilities" }); assert.equal(unsupported.status, 3); assert.equal(JSON.parse(unsupported.stdout).exitClass, "unsupported-contract"); });
test("validate-only is read-only and keeps stdout to one response", () => { const target = scratch(); try { const result = run(request(target, "validate", { draft: {} })); assert.equal(result.status, 0); assert.equal(result.stderr, ""); assert.equal(JSON.parse(result.stdout).result.ok, true); assert.equal(existsSync(join(target.cwd, ".pi", "gentle-ai", "models.json")), false); } finally { target.dispose(); } });
test("validate/apply reject legacy and nested draft shapes with stable paths", () => {
	const cases = [[{ worker: "demo/model" }, "worker"], [{ worker: { effort: "high" } }, "worker.effort"], [{ worker: null }, "worker"], [{ worker: "inherit" }, "worker"], [{ worker: { extra: "x" } }, "worker.extra"], [{ worker: { model: 7 } }, "worker.model"], [{ worker: { thinking: "inherit" } }, "worker.thinking"]] as const;
	for (const operation of ["validate", "apply"] as const) for (const [draft, path] of cases) {
		const target = scratch();
		try {
			const result = run(request(target, operation, { draft })), body = JSON.parse(result.stdout);
			assert.equal(result.status, 2); assert.equal(body.exitClass, "invalid-input");
			assert.deepEqual(body.result.diagnostics.map(({ code, path }: { code: string; path?: string }) => ({ code, path })), [{ code: "malformed-draft", path }]);
		} finally { target.dispose(); }
	}
});
test("project apply merges only the selected entries and never touches global/user state", () => { const target = scratch(), projectAgent = join(target.cwd, ".pi", "agents", "worker.md"), userAgent = join(target.agentDir, "agents", "user.md"); try { agent(projectAgent, "worker"); agent(userAgent, "worker"); const result = run(request(target, "apply", { draft: { worker: {} } })); assert.equal(result.status, 0); const body = JSON.parse(result.stdout).result; assert.equal(body.outcome, "success"); assert.deepEqual(JSON.parse(readFileSync(join(target.cwd, ".pi", "gentle-ai", "models.json"), "utf8")), { worker: {} }); assert.equal(existsSync(join(target.cwd, ".pi", "subagents.json")), true); assert.equal(existsSync(join(target.agentDir, "subagents.json")), false); assert.equal(readFileSync(userAgent, "utf8").includes("model:"), false); } finally { target.dispose(); } });
test("malformed routing and profile files fail closed without changing bytes", () => { const target = scratch(), config = join(target.cwd, ".pi", "gentle-ai", "models.json"), profile = join(target.cwd, ".pi", "subagents.json"); try { mkdirSync(join(target.cwd, ".pi", "gentle-ai"), { recursive: true }); writeFileSync(config, "{broken"); let result = run(request(target, "apply", { draft: { worker: {} } })); assert.equal(result.status, 5); assert.equal(readFileSync(config, "utf8"), "{broken"); rmSync(config); agent(join(target.cwd, ".pi", "agents", "worker.md"), "worker"); mkdirSync(join(target.cwd, ".pi"), { recursive: true }); writeFileSync(profile, "{broken-profile"); result = run(request(target, "apply", { draft: { worker: {} } })); assert.equal(result.status, 5); assert.equal(readFileSync(profile, "utf8"), "{broken-profile"); assert.equal(existsSync(config), false); } finally { target.dispose(); } });
test("persistence failure and partial materialization have distinct outcomes", () => { const target = scratch(), blocked = join(target.root, "not-a-directory"), worker = join(target.cwd, ".pi", "agents", "worker.md"); try { writeFileSync(blocked, "keep"); const failed = run({ ...request(target, "apply", { draft: {} }), target: "global", configHome: blocked }); assert.equal(failed.status, 5); assert.equal(readFileSync(blocked, "utf8"), "keep"); agent(worker, "worker"); chmodSync(worker, 0o444); const partial = run(request(target, "apply", { draft: { worker: { thinking: "high" } } })); assert.equal(partial.status, 6); const body = JSON.parse(partial.stdout).result; assert.equal(body.ok, false); assert.equal(body.outcome, "partial"); assert.equal(body.saved, true); assert.ok(body.materialization.succeeded.some((path: string) => path.endsWith("subagents.json"))); assert.ok(body.materialization.failed.some((path: { target: string }) => path.target === worker)); } finally { try { chmodSync(worker, 0o644); } catch {} target.dispose(); } });
test("startup materialization without a target reaches project-local agents", async () => { const target = scratch(), projectAgent = join(target.cwd, ".pi", "agents", "startup-project-agent.md"); try { agent(projectAgent, "startup-project-agent"); const result = await applyModelConfigAsync(target.cwd, { "startup-project-agent": { model: "demo/startup" } }, { agentDir: target.agentDir }); assert.equal(result.failed.length, 0); assert.ok(result.succeeded.includes(projectAgent)); assert.match(readFileSync(projectAgent, "utf8"), /model: demo\/startup/); } finally { target.dispose(); } });
test("the packed manifest ships the public bin and runtime", () => { const manifest = JSON.parse(readFileSync(join(root, "package.json"), "utf8")); assert.equal(manifest.bin["gentle-pi-models"], "./bin/gentle-pi-models.mjs"); const packed = spawnSync("npm", ["pack", "--dry-run", "--json", "--ignore-scripts"], { cwd: root, encoding: "utf8" }); assert.equal(packed.status, 0, packed.stderr); const files = JSON.parse(packed.stdout)[0].files.map((entry: { path: string }) => entry.path); assert.ok(files.includes("bin/gentle-pi-models.mjs")); assert.ok(files.includes("runtime/gentle-pi-models.ts")); });
test("packed runner proves the installed models executable", () => { const packedRunner = readFileSync(join(root, "scripts", "test-packed-runner.mjs"), "utf8"); assert.match(packedRunner, /gentle-pi-models/); assert.match(packedRunner, /gentle-pi\.model-routing\/v1/); assert.match(packedRunner, /capabilities/); });
